"""
Configuración del juego Jumpy Game.
Centraliza todas las constantes y configuraciones.
"""

import os

# === CONFIGURACIÓN DE PANTALLA ===
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
FPS = 60

# === CONFIGURACIÓN DE FÍSICA ===
SCROLL_THRESH = 200
GRAVITY = 1
MAX_PLATFORMS = 10

# === SISTEMA DE VIDAS ===
LIVES = 3
MAX_LIVES = 5

# === VELOCIDADES DE SALTO ===
INITIAL_JUMP_VEL = -20
BOOST_JUMP_VEL = -60

# === PROBABILIDADES DE SPAWN ===
BOOSTER_SPAWN_CHANCE = 0.08  # 8%
EXTRA_LIFE_SPAWN_CHANCE = 0.05  # 5%

# === REQUISITOS DE SCORE ===
MOVING_PLATFORMS_SCORE = 1000
BOOSTER_SCORE = 1000
ENEMY_SCORE = 2000

# === COLORES ===
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

# === RUTAS DE ARCHIVOS ===
CURRENT_DIR = os.path.dirname(__file__)
ASSETS_DIR = os.path.join(CURRENT_DIR, 'assets')
SCORE_FILE = os.path.join(CURRENT_DIR, 'score.txt')

# === CONFIGURACIÓN DE JUGADOR ===
PLAYER_IMAGE_SIZE = (48, 48)
PLAYER_COLLISION_SCALE = 0.7
PLAYER_SPEED = 10
PLAYER_START_X = SCREEN_WIDTH // 2
PLAYER_START_Y = SCREEN_HEIGHT - 150
